title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://cloudnationhq.github.io/terraform-azure-wam-website

aux_links:
  Template Repository: https://github.com/CloudNationHQ/terraform-azure-wam-website

plugins:
  - jekyll-default-layout